bardinux-system-restore-tool:     - Added configuration variable to define default user shell and home directory permissions for new users.     - Modified script that parses the configuration to include all variables.     - Added warning to notice the deletion of inactivity users.

diff --git a/bardinux-system-restore-tool/gcs/newfiles_skel/etc/initramfs-tools/hooks/parse-conf b/bardinux-system-restore-tool/gcs/newfiles_skel/etc/initramfs-tools/hooks/parse-conf
--- a/bardinux-system-restore-tool/gcs/newfiles_skel/etc/initramfs-tools/hooks/parse-conf
+++ b/bardinux-system-restore-tool/gcs/newfiles_skel/etc/initramfs-tools/hooks/parse-conf
@@ -17,19 +17,23 @@ esac
 
 . /usr/share/initramfs-tools/hook-functions
 
-[ -e /etc/default/bsrt ] && . /etc/default/bsrt
+[ -e /etc/default/bsrt ] || { echo "ERROR: File /etc/default/bsrt not found!"; exit 1 }
+
+. /etc/default/bsrt
 
 echo -n "Parsing configuration... "
+
+sed '/BACKUP_DEVICE/d' /etc/default/bsrt > ${DESTDIR}/etc/default/bsrt 
 
 interval=$(awk '$0 !~ /^ *#/ && $1 == "interval" { print $2 }' /etc/rsnapshot.conf)
 root_dev=$(awk '$0 !~ /^ *#/ && $2 == "/" { print $1 }' /etc/fstab)
 backup_dev=${BACKUP_DEVICE:-$root_dev}
 
-cat > ${DESTDIR}/etc/default/bsrt << EOF
+cat >> ${DESTDIR}/etc/default/bsrt << EOF
+# Internal variables
 INTERVAL=${interval}
 ROOTDEV=${root_dev}
 BACKUPDEV=${backup_dev}
-BACKTITLE="${SCREEN_BACKTITLE}"
 EOF
 
 echo "done!"
